package BitManipulation;

/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */
public class FindtheDifference {
	public char findTheDifference(String s, String t) {
        /*int result = 0;
		int[] alpha = new int[26];
        for (int i = 0; i < s.length(); i++) {
            alpha[s.charAt(i) - 'a']++;
            alpha[t.charAt(i) - 'a']--;
        }
        alpha[t.charAt(s.length()) - 'a']--;
        for (int j = 0; j < alpha.length; j++) {
            if (alpha[j] != 0) {
            	result = j;
            }
        }
		return (char)('a' + result);*/
		char result = 0;
        for (int i = 0; i < s.length(); i++) {
        	result ^= s.charAt(i);
        	result ^= t.charAt(i);
        }
        result ^= t.charAt(t.length() - 1);
        return result;
    }
}
